version: "3.9"
services:
  user-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    ports:
      - "3005:3000"
    env_file:
      - ./packages/db/.env

  bank-webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.bank-webhook
    ports:
      - "4000:3000"
    env_file:
      - ./packages/db/.env