version: "3.9"
services:
  user-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    ports:
      - "3005:3000"
    env_file:
      - ./packages/db/.env
    depends_on:
      - bank-webhook
    networks:
      - pakpay-network

  bank-webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile.bank-webhook
    ports:
      - "4000:3003"
    env_file:
      - ./packages/db/.env
    networks:
      - pakpay-network

networks:
  pakpay-network:
    driver: bridge