FROM node:20

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./
COPY apps/socket-gateway ./apps/socket-gateway
COPY packages ./packages

RUN npm ci

WORKDIR /usr/src/app/apps/socket-gateway
RUN npm run build

WORKDIR /usr/src/app

ENV NODE_ENV=production
CMD ["node", "apps/socket-gateway/dist/notification-server.js"]
